title: "CV page - Sangdon Lim"
description: ""
url: "https://sdlim.com"
base_url: ""

header_pages:
  - index.md

markdown: kramdown
remote_theme: SangdonLim/jekyll-theme-console

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag